title: "I Love E-Poetry"
description: "Short form scholarship on born-digital poetry."
url: "https://iloveepoetry.org"
baseurl: ""
author: "Leonardo Flores"

# Build
future: true
markdown: kramdown
highlighter: rouge

# Pagination
pagination:
  enabled: false
  per_page: 12
  permalink: "/page-:num/"
  title: ":title"
  sort_field: "date"
  sort_reverse: true

# Plugins
plugins:
  - jekyll-paginate-v2

# Default front matter
defaults:
  - scope:
      path: "_posts/en"
    values:
      lang: "en"
      layout: post
  - scope:
      path: "_posts/es"
    values:
      lang: "es"
      layout: post
  - scope:
      path: "_pages/en"
      type: "pages"
    values:
      lang: "en"
      layout: page
  - scope:
      path: "_pages/es"
      type: "pages"
    values:
      lang: "es"
      layout: page

# Collections
collections:
  pages:
    output: true

# Exclude from build
exclude:
  - scripts/
  - Gemfile
  - Gemfile.lock
  - "*.py"
  - README.md
  - vendor
  - node_modules
