#!/usr/bin/env python3
"""
Download all images referenced in the WordPress export and post content.
Reads image_urls.txt (generated by convert_wp.py) and downloads to local assets.
"""

import json
import os
import re
import sys
import time
import logging
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path
from urllib.parse import urlparse, unquote

import requests

# Configuration
PROJECT_DIR = Path(__file__).resolve().parent.parent
SCRIPTS_DIR = PROJECT_DIR / "scripts"
ASSETS_DIR = PROJECT_DIR / "assets" / "images"
IMAGE_URLS_FILE = SCRIPTS_DIR / "image_urls.txt"
MANIFEST_FILE = SCRIPTS_DIR / "image_manifest.json"
FAILURES_LOG = SCRIPTS_DIR / "download_failures.log"

MAX_WORKERS = 5
TIMEOUT = 30
MAX_RETRIES = 3
RETRY_BACKOFF = 2  # seconds, doubled each retry

USER_AGENT = (
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
    "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
)

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
)
logger = logging.getLogger(__name__)


def url_to_local_path(url):
    """Map a URL to a local file path under assets/images/."""
    parsed = urlparse(url)
    host = parsed.hostname or ""
    path = unquote(parsed.path).lstrip("/")

    if "iloveepoetry" in host and "wp-content/uploads/" in path:
        # Preserve wp-content/uploads/YYYY/MM/filename structure
        idx = path.index("wp-content/uploads/")
        rel = path[idx:]
        return ASSETS_DIR / rel

    if "academic.uprm.edu" in host and "/flores/images/" in path:
        filename = path.split("/flores/images/")[-1]
        return ASSETS_DIR / "uprm" / filename

    # Fallback: store under assets/images/other/hostname/path
    safe_path = path.replace("..", "_")
    return ASSETS_DIR / "other" / host / safe_path


def should_skip(url):
    """Return True if this URL should not be downloaded."""
    parsed = urlparse(url)
    host = parsed.hostname or ""

    # Skip localhost development artifacts
    if host in ("localhost", "127.0.0.1"):
        return True

    # Skip non-image/non-asset URLs
    # We download images, PDFs, videos, GIFs
    return False


def download_file(url, local_path, session):
    """Download a single file with retry logic. Returns (url, local_path, success, error)."""
    if should_skip(url):
        return (url, str(local_path), False, "skipped: localhost/dev URL")

    # Check if already downloaded
    if local_path.exists() and local_path.stat().st_size > 0:
        return (url, str(local_path), True, "already exists")

    # Ensure parent directory exists
    local_path.parent.mkdir(parents=True, exist_ok=True)

    last_error = None
    for attempt in range(MAX_RETRIES):
        try:
            resp = session.get(
                url,
                timeout=TIMEOUT,
                headers={"User-Agent": USER_AGENT},
                stream=True,
                allow_redirects=True,
            )
            resp.raise_for_status()

            with open(local_path, "wb") as f:
                for chunk in resp.iter_content(chunk_size=8192):
                    f.write(chunk)

            size = local_path.stat().st_size
            if size == 0:
                local_path.unlink()
                return (url, str(local_path), False, "empty file")

            return (url, str(local_path), True, None)

        except requests.exceptions.RequestException as e:
            last_error = str(e)
            if attempt < MAX_RETRIES - 1:
                wait = RETRY_BACKOFF * (2 ** attempt)
                time.sleep(wait)

    return (url, str(local_path), False, last_error)


def collect_urls_from_file(filepath):
    """Read image URLs from the text file, one per line."""
    urls = set()
    if not filepath.exists():
        logger.error(f"Image URLs file not found: {filepath}")
        logger.info("Run convert_wp.py first to generate image_urls.txt")
        sys.exit(1)

    with open(filepath, "r", encoding="utf-8") as f:
        for line in f:
            url = line.strip()
            if url and url.startswith("http"):
                urls.add(url)

    return urls


def collect_urls_from_posts():
    """Scan generated Jekyll posts for any additional image URLs not in the list."""
    urls = set()
    img_pattern = re.compile(r'(?:src|href)=["\']([^"\']+\.(?:png|jpg|jpeg|gif|pdf|mp4|tif|webp))["\']', re.I)

    for lang_dir in (PROJECT_DIR / "_posts" / "en", PROJECT_DIR / "_posts" / "es"):
        if not lang_dir.exists():
            continue
        for post_file in lang_dir.glob("*.html"):
            content = post_file.read_text(encoding="utf-8", errors="replace")
            for match in img_pattern.finditer(content):
                url = match.group(1)
                if url.startswith("http"):
                    urls.add(url)

    return urls


def main():
    logger.info("=== Image Download Script ===")
    logger.info(f"Project dir: {PROJECT_DIR}")
    logger.info(f"Assets dir: {ASSETS_DIR}")

    # Collect all image URLs
    urls_from_file = collect_urls_from_file(IMAGE_URLS_FILE)
    urls_from_posts = collect_urls_from_posts()
    all_urls = urls_from_file | urls_from_posts

    # Filter out skippable URLs
    download_urls = [u for u in all_urls if not should_skip(u)]
    skipped_urls = [u for u in all_urls if should_skip(u)]

    logger.info(f"Total unique URLs: {len(all_urls)}")
    logger.info(f"URLs to download: {len(download_urls)}")
    logger.info(f"Skipped (localhost etc): {len(skipped_urls)}")

    # Build download tasks
    tasks = []
    for url in sorted(download_urls):
        local_path = url_to_local_path(url)
        tasks.append((url, local_path))

    # Download with thread pool
    manifest = {}
    failures = []
    already_existed = 0
    downloaded = 0

    session = requests.Session()

    logger.info(f"Starting downloads with {MAX_WORKERS} workers...")

    with ThreadPoolExecutor(max_workers=MAX_WORKERS) as executor:
        futures = {
            executor.submit(download_file, url, path, session): (url, path)
            for url, path in tasks
        }

        for i, future in enumerate(as_completed(futures), 1):
            url, local_path_str, success, error = future.result()

            if success:
                if error == "already exists":
                    already_existed += 1
                else:
                    downloaded += 1
                # Store relative path from project root
                rel_path = os.path.relpath(local_path_str, PROJECT_DIR)
                manifest[url] = rel_path
            else:
                failures.append({"url": url, "error": error})

            if i % 50 == 0:
                logger.info(f"Progress: {i}/{len(tasks)} ({downloaded} new, {already_existed} cached, {len(failures)} failed)")

    # Also add skipped URLs to manifest with null path
    for url in skipped_urls:
        manifest[url] = None

    # Write manifest
    with open(MANIFEST_FILE, "w", encoding="utf-8") as f:
        json.dump(manifest, f, indent=2, ensure_ascii=False)

    # Write failures log
    with open(FAILURES_LOG, "w", encoding="utf-8") as f:
        for fail in failures:
            f.write(f"{fail['url']}\t{fail['error']}\n")

    # Summary
    logger.info("=== Download Complete ===")
    logger.info(f"Newly downloaded: {downloaded}")
    logger.info(f"Already existed: {already_existed}")
    logger.info(f"Failed: {len(failures)}")
    logger.info(f"Skipped: {len(skipped_urls)}")
    logger.info(f"Manifest: {MANIFEST_FILE}")
    logger.info(f"Failures log: {FAILURES_LOG}")

    if failures:
        logger.warning(f"Failed downloads ({len(failures)}):")
        for fail in failures[:20]:
            logger.warning(f"  {fail['url']}: {fail['error']}")
        if len(failures) > 20:
            logger.warning(f"  ... and {len(failures) - 20} more (see {FAILURES_LOG})")


if __name__ == "__main__":
    main()
